Windows GUI: Use file folder and name as export default for single file
MediaArea/MediaInfo pull request #847
Opened 2024-05-28 16:10 UTC by cjee21

When only a single file is open in MediaInfo, use that file's name and folder as the default when exporting instead of MediaInfo's AppData directory.

Not sure if can consider issue #741 as resolved since this PR is only for when there is a single file open.

2024-05-28 17:05 UTC, JeromeMartinez requested changes
there is a risk to overwrite the original file (there is now a warning if the file exist, but default to an existing file is a source of problems as people use to click on every window box).
Please append ".MediaInfo.xml" (if XML output, else ".txt" etc).

2024-05-29 07:00 UTC, cjee21 commented
Made the change. Now it will retain the file extension and add .mediainfo before the exported file extension. So even if user has files with same name but one is .mp4 and another .mkv for example, there is also no risk of overwrite.

2024-05-29 10:40 UTC, JeromeMartinez commented
> Now: my test file.mp4.mediainfo.txt

Oops, I missed that the extension is already there.
Please "mediainfo" --> "MediaInfo" (I am a uppercase letters addict).

2024-05-29 10:51 UTC, JeromeMartinez approved these changes

2024-05-29 11:33 UTC, merged