Qt GUI: Fixes and improvements 2
MediaArea/MediaInfo pull request #955
Opened 2024-11-14 12:47 UTC by cjee21

Qt GUI: Revert 'Make Text view editable'
- Revert commit b9fbf9ec8aa9e15bebcc87eb4fe102f47fe56f5f as it broke drag and drop of files into the text view. Text view isn't supposed to be editable anyway so match the wxWidgets version instead of VCL one.

Qt GUI: Add legacy stream display option
- An option that is present in MediaInfoLib and CLI but not yet in the GUI
- Disabled by default

![Screenshot 2024-11-14 204655](https://github.com/user-attachments/assets/a88e0977-be1a-453c-b2a8-2ba6d1129331)

2024-11-14 13:34 UTC, cjee21 commented
**Current state of Qt GUI after this PR:**

Better compared to VCL GUI:
- More native looking dark mode and seamless switching
- Option to remember window size, position and state
- No cropped text in easy view
- Text wrapping in text view
- CFG and CET enabled for entire GUI
- Legacy stream display option available
- Preferences window can be resized usefully (contents expand to make full use of the space)
- Faster compilation time
- Seems to be smoother with less graphics glitches
- Easy integration with modern Windows context menu

Lacking compared to VCL GUI:
- No graph view
- No FFmpeg plugin support
- Requires bundling Qt WebEngine on Windows
- No translations
- Shell InfoTip setting does nothing at the moment

2024-11-15 09:05 UTC, JeromeMartinez commented
It is great!
I am still reluctant for the full migration on Windows, especially for the HTML part (need to find something for that), but if you keep improving Qt I guess that I will at least drop the Wx version and put Qt version on all Linux platforms and also for the free version on macOS at some point...

> Easy integration with modern Windows context menu

How is it possible? Qt stuff? Not possible to use the same with the VCL version?

> No temporary file generated in %TEMP% for HTML and Graph view

Same, not something doable with VCL too?

2024-11-15 09:06 UTC, JeromeMartinez requested changes
Please remove the build/* files

2024-11-15 09:07 UTC, cjee21 commented
> Please remove the build/* files

Ooops, accidentally included. I thought I had checked files that were included.

2024-11-15 15:38 UTC, JeromeMartinez approved these changes

2024-11-15 15:38 UTC, merged

2024-11-15 15:40 UTC, JeromeMartinez commented
> By the way, should I implement the legacystreamdisplay option for the VCL version too?

Yes.
At some point the call to options will be though MediaInfoLib for avoiding duplicated code, but it is a good thing to have everything in sync before doing this work.